Sujit postgresassignment
adityajawade93/freshers-june2021 pull request #34
Opened 2021-07-07 07:17 UTC by ksujit911

2021-07-08 10:42 UTC, anoophm requested changes

2021-07-08 10:42 UTC, anoophm commented on .gitignore
> +node_modules/
can you also use tslint to format the code

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +export var getstudentsbyclass = async (ctx: any) => {
we should use cameCase for naming function and variables. getStudentsByClassId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +    var std = await ctx.params.std
can use let and const and not use var. what is std here, is it classId or studentId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +    if (std === "null" || std === "undefined") {
if url has /:std then std will always be present, otherwise request will not come to this function.

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +        var res = await classservice.getstudentsbyclass(std)
getStudentsByClassId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +
no need to keep empty line can you use lint to fix this.

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +
dont we need a api to create class

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +        if (req.cstudentid != null && req.cstandard != null && typeof req.cstandard == 'number' && typeof req.cstudentid == 'string') {
can you create one if block and do all validation if it has error and return inside the if block by sending error. Adding if inside if is not readable. Check Druval PR once

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/classes.ts
> +            var res = await classservice.addstudentstoclass(req.cstudentid, req.cstandard)
if this function return error how are we catching this. we need to use try catch block. Check Druval PR

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    if (studentid === "null" || studentid === "undefined") {
check all the comments in class controller and do it here also

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    if (studentid === "null" || studentid === "undefined") {
check druval pr and lets discuss if you have doubt on async await and error handling.

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +export var gethighestmarks = async (ctx: any) => {
getHightMarkBySubjectId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    var subjectname: any = await ctx.query.subject
we dont need to use await here, its just a object

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    var std: any = await ctx.query.std
same here

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +        var res = await marksservice.gethighestmarks(subjectname, std)
why do we need subjectId and subjectName. subjectId should be enough to query right

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +export var createmarks = async (ctx: any) => {
addMarks

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +export var createmarks = async (ctx: any) => {
and we might need one more api to update marks also

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +export var createmarks = async (ctx: any) => {
can you use Context interface instead of any

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    if (req.rsid && req.rstd && req.rsubject && req.rmarks) {
check the comments in marks controller

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +            var res = await marksservice.createmarks(req.rsid, req.rstd, req.rsubject, req.rmarks)
cant we send req object instead of sending 3 params

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    rsid: string
studentId
subjectId
marks or score
what is rstd

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +type results = {
IResult

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +    rsid: string
dont use sid, rid. keep fullform

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +            var res = await marksservice.createmarks(req.rsid, req.rstd, req.rsubject, req.rmarks)
there no proper error handling here and error message sent back wont be helpfull. all are generic message

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/marks.ts
> +        if (req.rsid != null && req.rstd != null && req.rsubject != null && req.rmarks != null
check out https://joi.dev/api/?v=17.4.0 for doing request body validation. Check Druval pr for the same. Do it for few request.

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/sechdule.ts
> +export var getsechdulebyclass = async (ctx: any) => {
check the comments in other controllers

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +        var res = await studentservice.getstudents()
we need pagination here

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +        var studentsrows = await res.rows
no need to use await here

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +        ctx.body = JSON.stringify(studentsrows, null, 2)
can you set content type to json and send object, instead of stringify

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +export var getstudentbysid = async (ctx: any) => {
getStudentById

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +export var getstudentbysid = async (ctx: any) => {
is it studentId or subjectId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +export var getstudentsbytid = async (ctx: any) => {
getStudentByTeacherId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +export var getstudentsbysubname = async (ctx: any) => {
we dont need this, should be based subjectId

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +    var req: studenttype = ctx.request.body
IStudent

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +    var fname, lname, dob
use let and no need to keep them in separate variables use req.firstName

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/controller/students.ts
> +    if (req.fname && req.dateofbirth) {
all this validation can be done using Joi. Try it out

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/database/clientdb.ts
> +        throw new Error(er)
no need to catch and throw same error, just return pool.query

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/routes/routes.ts
> +router.get('/school/students', student.getstudents)
/student

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/routes/routes.ts
> +router.get('/school/studentsbytid/:teacherid',student.getstudentsbytid)
/teacher/:teacherId/students

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/routes/routes.ts
> +router.get('/school/studentsbysub/:subjectname',student.getstudentsbysubname)
/subject/:subjectId/student

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/routes/routes.ts
> +router.get('/school/studentsbysub/:subjectname',student.getstudentsbysubname)
use similar pattern for all the api's. we can discuss on this.

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/services/classes.ts
> +        throw new Error(e)
u need handle error and send appropriate message and code. Talk to Druval once

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/services/marks.ts
> +        var res = await query(`select studentid,rstd,fname,sum(rmarks)
check https://sequelize.org/master/ for making db operation. It provide functions to do CRUD. Try out in few places, no need to do for all place

2021-07-08 10:42 UTC, anoophm commented on sujit/school/src/sql/schooldb.sql
> +alter table sechdule add foreign key(tid) references teachers(teacherid);
keep full name teacherId

2021-07-08 11:24 UTC, ksujit911 commented on .gitignore
> +node_modules/
sure sir i will add it

2021-07-08 11:29 UTC, ksujit911 commented on sujit/school/src/controller/classes.ts
> +    var std = await ctx.params.std
sir it is standard 11th class 12 class like that

2021-07-26 06:16 UTC, arjunjgowda commented on sujit/school/src/database/clientdb.ts
> +    console.log("postgressql error event")
We should be throwing error if connection fails. Because application can no longer work if db connection fails.

2021-07-26 07:29 UTC, merged