postgres assignment
adityajawade93/freshers-june2021 pull request #36
Opened 2021-07-07 17:03 UTC by rnishant97

2021-07-07 19:18 UTC, anoophm requested changes

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/app/index.ts
> +app.use(studentrouter.routes());
we can use combineRoute method instead of adding each route individually

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/app/index.ts
> +let app=new Koa();
maybe use const instead of let since we dont change the value of app

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/class.ts
> +interface  class_schedule_data{
use camelcase for all interface, classes and prefix with I. Like ISchedule

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/class.ts
> +    class_id:number;
classId

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/class.ts
> +interface student_details_data{
IStudentDetails

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/class.ts
> +        if(req.class_id===undefined || req.studid===undefined || typeof req.class_id!=='number' || typeof req.studid!=='number'){
we can use json validation library like Joi to validate request body. Try it out for few api's no need to do it for all apis'. 
https://joi.dev/api/?v=17.4.0

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/class.ts
> +    try{
can we format this file, we can use linting to do this, check how we can do this.

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/general.ts
> +export async function gettopperByclassIdAndSubjectId(ctx: Context){
use camelcase for naming function, variables

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/general.ts
> +    student_id:number;
camelcase

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/general.ts
> +        var c_id=parseInt(ctx.params.c_id);
use let and use object de structuring here
link for de structuring https://javascript.info/destructuring-assignment

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/schedule.ts
> +interface  class_schedule_data{
here also, check above comments

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/student.ts
> +      rows=await  studentService.get_student();
we shouldnt fetch everything from db and filter the result, can check how we can do pagination using db method, there limit and offset function in db.

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/controller/student.ts
> +      rows=await  studentService.get_student();
refer here https://github.com/adityajawade93/freshers-june2021/blob/e40de5ff0c6ecf17031c61a5c166caffb87aa0df/druval_cr/postgresAssignment/src/services/student.ts#L32

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/class.ts
> +router.post('/createclass_student',addStudentInClass);
/class/:classId/student and the method post says its create

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/general.ts
> +router.get('/topclass/:c_id/topsubject/:s_id',gettopperByclassIdAndSubjectId);
/toppers/class/:classId/subject/:subjectId

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/general.ts
> +router.get('/topten/:c_id/number/:num',gettopstudent);
/topper/class/:classId/:count

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/result.ts
> +router.post('/createresult',addResult);
just /result and method post implies its a create

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/result.ts
> +router.put('/updateresult',updateResult);
just /result and method put implies its a update

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/schedule.ts
> +router.post('/createclass_schedule',addClassSchedule);
check result route comment

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/routes/student.ts
> +router.post('/createstudent',addStudent);
same here also

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/services/class.ts
> +export async function get_class(){
naming convention

2021-07-07 19:18 UTC, anoophm commented on Nishant/Day_12/postgres assignment/src/services/general.ts
> +    await sqlclient.query("SET search_path TO College");
we can use ORM's like https://joi.dev/api/?v=17.4.0 to do db operation. 
Try this out, no need to do this changes to this assignment

2021-07-26 07:06 UTC, arjunjgowda commented on Nishant/postgres assignment/package.json
> +  "main": "index.js",
update main file . ref :  https://github.com/adityajawade93/freshers-june2021/tree/main/jatin/postgres_assignment

2021-07-26 07:07 UTC, arjunjgowda commented on Nishant/postgres assignment/schema.sql
> +    CREATE TABLE Student(student_id int PRIMARY KEY NOT NULL,fname text NOT NULL,mname text NULL,lname text NULL,dob date NOT NULL,gender sex NOT NULL,address text NOT NULL);
discuss with jatin/tarun for schema changes. Update all your data types.

2021-07-26 07:09 UTC, arjunjgowda commented on Nishant/postgres assignment/src/controller/class.ts
> +    await validateclass.getStudentByClassIdSchema.validateAsync(classId);
keep validation and db call with seperate try/catch block.

2021-07-26 07:09 UTC, arjunjgowda commented on Nishant/postgres assignment/src/controller/class.ts
> +    if (e.isJoi === true) {
Follow above comment.

2021-07-26 07:09 UTC, arjunjgowda commented on Nishant/postgres assignment/src/controller/general.ts
> +  let { classId, count }:{classId:number, count:number} = ctx.params;
Better to validate input data before using it.

2021-07-26 07:12 UTC, arjunjgowda commented on Nishant/postgres assignment/src/controller/result.ts
> +    if (e.isJoi === true) {
same as above...

2021-07-26 07:13 UTC, arjunjgowda commented on Nishant/postgres assignment/src/controller/schedule.ts
> +      ctx.response.status = 422;
why 422 ? should it be 400 ?

2021-07-26 07:15 UTC, arjunjgowda commented on Nishant/postgres assignment/src/controller/student.ts
> +    const rows:QueryResult = await studentService.getStudentService();
you can use exception handling only for those statements that would raise exception... keeping all the statements inside try/catch would not tell me immediately as to what will raise exception...

2021-07-26 07:16 UTC, arjunjgowda commented on Nishant/postgres assignment/src/services/class.ts
> +export async function getClassService() {
service would not be required in method name. Please remove.

2021-07-26 07:17 UTC, arjunjgowda commented on Nishant/postgres assignment/src/services/class.ts
> +    await sqlclient.query('SET search_path TO College');
search_path can be replaced. ref : https://github.com/adityajawade93/freshers-june2021/tree/main/jatin/postgres_assignment or feel free to get in touch with jatin/tarun...

2021-07-26 07:18 UTC, arjunjgowda commented on Nishant/postgres assignment/src/services/general.ts
> +    return (await sqlclient.query(`SELECT student_id,fname,S.marks FROM (SELECT * FROM result WHERE clas_id=${classId} AND subjectid=${subjectId} ORDER BY marks DESC) AS S,Student WHERE S.studentid=s
select would always return data in random order so use order by in all queries.

2021-07-26 11:31 UTC, arjungowda-kr commented on Nishant/postgres assignment/src/services/result.ts
> +  try {
why will we need try/catch here ?

2021-07-27 11:24 UTC, arjungowda-kr requested changes

2021-07-27 11:24 UTC, arjungowda-kr commented on Nishant/postgres assignment/src/controller/student.ts
> +    if (page === undefined || size === undefined || typeof page !== 'number' || typeof size !== 'number') {
when will page and size be undefined ?

2021-07-27 11:24 UTC, arjungowda-kr commented on Nishant/postgres assignment/src/server.ts
> +require('dotenv').config({ path: path.join(__dirname, '../.env') });
validate env ?

2021-07-27 12:59 UTC, merged